### ISSUE TITLE
error when running the code

### ISSUE THREAD

**Issue by poisonwine** [TianhongDai/div-hindsight#1]
hello,
     when I running the code, it reports an error like the following shows:
  
    marg= lmbda[i-1] * E[rem-1,i-1]/(E[rem,i]+1e-100)
    IndexError: index -101 is out of bounds for axis 0 with size 100

**Comment by TianhongDai** [comment]
Hi @poisonwine 

Could I know what is the command you run to generate this error, please?

**Comment by poisonwine** [comment]
I guess  I find the reason, maybe because I modified the batch_size from 64 into 256?
How should I change the code to use 256 batch_size?

**Comment by TianhongDai** [comment]
> I guess I find the reason, maybe because I modified the batch_size from 64 into 256? How should I change the code to use 256 batch_size?

Yes - I think that's the problem, you can increase the `subset_size` to 300 (any number larger than 256, but it will affect the efficiency) from [https://github.com/TianhongDai/div-hindsight/blob/master/baselines/her/experiment/train.py#L193](https://github.com/TianhongDai/div-hindsight/blob/master/baselines/her/experiment/train.py#L193).
